config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users, only: [:index, :show]
  
  resources :user_profiles, only: [:new, :create, :edit, :update]

  resources :templates

  get '/terms', to: 'pages#terms'
  get '/privacy', to: 'pages#privacy'

  resources :lessons do
    collection do
      post :sort
    end
  end

  resources :steps do
    collection do
      post :sort
    end
    get 'submit', on: :member
  end

  resources :fields do
    collection do
      post :sort
    end
  end

  resources :ideas do
    get :show_admin
  end

  # resources :plans do
  #   patch :unsubscribe

  #   get :edit_card
  #   patch :update_card
  #   patch :remove_card
  # end

  resources :plan_options

  authenticated :user do
    root :to => "ideas#index", as: :authenticated_root
  end

  root :to => "pages#landing"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :templates
  has_many :ideas, dependent: :destroy
  has_many :responses, dependent: :destroy

  has_one :plan, dependent: :destroy
  has_one :user_profile, dependent: :destroy

  def trial?
    if (DateTime.current <= (self.created_at + 30.days)) || self.admin?
      return true
    else
      return false
    end
  end

  def plan_capacity?
    # allow if still under the trial period or admin
    if self.trial? || self.admin?
      return true
    # check if there is a plan object and if it has capacity
    elsif self.plan
      current_idea_count = self.ideas.count
      current_plan = PlanOption.where(stripe_plan_id: self.plan.plan_id).first

      # if there is a matching plan to what the user has subscribed to
      if current_plan
        current_plan_max = current_plan.idea_max

        # check if the user has reached their limit
        if current_idea_count < current_plan_max
          return true
        else
          return false
        end
      else
        return false
      end

    # if no trial and no plan object
    else
      return false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  load_and_authorize_resource
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/views/users/index.html.haml
#users-overview
  .row
    .col-md-12
      .page-header
        %h1
          nafasi Users

  
  .row
    .col-md-12
      - @users.each do |user|
        .user
          %h4
            = link_to user.email, user
          - user.ideas.each do |user_idea|
            - progress = user_idea.pct_complete

            .user-idea
              .idea-status
                - if progress >= 100
                  %i.fa.fa-circle.completed
                - elsif progress <= 0
                  %i.fa.fa-circle-o.not-started
                - else
                  %i.fa.fa-circle-o.in-progress

              .idea-details
                = link_to user_idea.name, idea_show_admin_path(user_idea)

                .progress
                  - if progress >= 100
                    .progress-bar.progress-bar-info{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => progress, :role => "progressbar", :style => "width: #{progress.to_s}%;"}
                      = progress.to_s+'%'
                  - else
                    .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => progress, :role => "progressbar", :style => "width: #{progress.to_s}%;"}
                      = progress.to_s+'%'

app/views/users/show.html.haml
.row
  .col-md-12
    .page-header
      %h1
        = @user.email + "'s profile"

.row
  .col-md-12

    - if @user.user_profile
      .user_profile
        - if @user.user_profile.linkedin
          = link_to @user.user_profile.linkedin, target: "_blank" do
            %i.fa.fa-linkedin-square
            LinkedIn Profile

        - if @user.user_profile.profession
          = @user.user_profile.profession

        - if @user.user_profile.location
          = @user.user_profile.location