config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users, only: [:index, :show]
  
  resources :user_profiles, only: [:new, :create, :edit, :update]

  resources :templates

  get '/terms', to: 'pages#terms'
  get '/privacy', to: 'pages#privacy'

  resources :lessons do
    collection do
      post :sort
    end
  end

  resources :steps do
    collection do
      post :sort
    end
    get 'submit', on: :member
  end

  resources :fields do
    collection do
      post :sort
    end
  end

  resources :ideas do
    get :show_admin
  end

  # resources :plans do
  #   patch :unsubscribe

  #   get :edit_card
  #   patch :update_card
  #   patch :remove_card
  # end

  resources :plan_options

  authenticated :user do
    root :to => "ideas#index", as: :authenticated_root
  end

  root :to => "pages#landing"
end

app/models/plan_option.rb
class PlanOption < ActiveRecord::Base
  validates :stripe_plan_id, presence: true
  validates :title, presence: true
  validates :idea_max, presence: true
  validates :price, presence: true
end

app/controllers/plan_options_controller.rb
class PlanOptionsController < ApplicationController

  load_and_authorize_resource
  
  def index
    @plan_options = PlanOption.all
  end

  def new
    @plan_option = PlanOption.new
  end

  def create
    @plan_option = PlanOption.new(plan_option_params)

    if @plan_option.save
      redirect_to plan_options_path
    else
      render :new
    end
  end

  def edit
    @plan_option = PlanOption.find(params[:id])
  end

  def update
    @plan_option = PlanOption.find(params[:id])

    if @plan_option.update_attributes(plan_option_params)
      redirect_to plan_options_path
    else
      render :edit
    end
  end

  def destroy
    PlanOption.find(params[:id]).destroy
    redirect_to plan_options_path
  end


  private

    def plan_option_params
      params.require(:plan_option).permit(:title, :stripe_plan_id, :idea_max, :price)
    end
end

app/views/plan_options/_form.html.haml
= f.input :title, required: true
= f.input :stripe_plan_id, label: 'Stripe Plan Id (must match plan id created in Stripe)'
= f.input :idea_max, label: 'Maximum Number of Ideas'
= f.input :price

app/views/plan_options/edit.html.haml
.col-md-12
  .page-header
    %h1
      Edit
      = @plan_option.title

  = simple_form_for @plan_option do |f|
    = render partial: 'form', locals: { f: f }

    = button_tag(type: 'submit', class: "btn btn-primary btn-lg") do
      %i.fa.fa-check-circle-o
      Modify Plan

app/views/plan_options/index.html.haml
.row
  .col-md-12
    .page-header
      %h1
        nafasi Plans

    = link_to 'Add New Plan', new_plan_option_path, class: "btn btn-primary btn-lg"
    = link_to 'Stripe Dashboard', "https://dashboard.stripe.com/", target: "_blank", class: "btn btn-info btn-lg"

.row
  .col-md-12
    .table-wrapper
      %table.table
        %thead
          %tr
            %th Title
            %th Stripe ID
            %th Price
            %th Max Ideas
            %th Options
        %tbody
          - @plan_options.each do |plan_option|
            %tr
              %td
                = plan_option.title
              %td
                = plan_option.stripe_plan_id
              %td  
                = number_to_currency(plan_option.price)
              %td
                = plan_option.idea_max
              %td
                = link_to 'Edit', edit_plan_option_path(plan_option)
                = link_to 'Delete', plan_option, method: :delete, data: { confirm: 'Are you sure you want to delete '+plan_option.title+'? Note: You must also remove the plan via the Stripe dashboard' }, title: 'delete '+plan_option.title, class: 'plan_option-delete'

app/views/plan_options/new.html.haml
.col-md-12
  .form-content
    .form-header
      %h1 Create New Plan
      
    .form-body
      = simple_form_for @plan_option do |f|
        = render partial: 'form', locals: { f: f }

        = button_tag(type: 'submit', class: "btn btn-primary btn-lg") do
          %i.fa.fa-check-circle-o
          Add Plan